#Specify the DataSource Type (HikariCp)

spring: 
   datasource: 
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/ankit
     username: root
     password: ankit@123