#Specify the DataSource Type (dbcp2)

spring:
   datasource:
     type: org.apache.commons.dbcp2.BasicDataSource

     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/ankit
     username: root
     password: ankit@123